version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: yrgyz_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yrgyz_taxi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: yrgyz_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/yrgyz_taxi
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

volumes:
  postgres_data:
